name: 'File Filter'
description: 'Filter PR files by glob patterns and return true/false if any files match'
inputs:
  patterns:
    description: 'String containing one or more glob patterns separated by spaces'
    required: true
  token:
    description: 'GitHub token for API access'
    required: false
    default: ${{ github.token }}
  base_ref:
    description: 'Base reference for comparison (defaults to PR base or main branch)'
    required: false
  head_ref:
    description: 'Head reference for comparison (defaults to PR head or current branch)'
    required: false
outputs:
  matches:
    description: 'True if any files match the patterns, false otherwise (boolean)'
  count:
    description: 'Number of files that matched the patterns (integer)'
  files:
    description: 'Files that matched the patterns (JSON array of strings)'
runs:
  using: 'docker'
  image: 'Dockerfile'
